sonar.projectKey=banco-digital-reporting
sonar.projectName=Banco Digital - Reporting Service
sonar.projectVersion=${project.version}
sonar.organization=codefactory-udea-v20261
sonar.sources=src/main/java,src/main/resources
sonar.tests=src/test/java
sonar.sourceEncoding=UTF-8
sonar.java.binaries=target/classes
