spring:
  datasource:
    # Local development - Reporting user
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:banco_digital_reporting}
    username: report_user
    password: ${REPORTING_DB_PASSWORD:changemeinlocalenv}
  cloud:
    vault:
      enabled: false
  jpa:
    show-sql: true

spring.kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
  consumer:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}



logging:
  level:
    com.udea.bancodigital: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
