spring:
  datasource:
    url: jdbc:postgresql:///${DB_NAME:banco_digital_reporting}?cloudSqlInstance=${CLOUD_SQL_INSTANCE}&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=${DB_USERNAME:report_user}&password=${DB_PASSWORD:ReportingBD101!}
  jpa:
    show-sql: false

logging:
  level:
    root: WARN
    com.udea.bancodigital: INFO

server:
  error:
    include-message: never
    include-stacktrace: never

eureka:
  client:
    enabled: false
    registerWithEureka: false
    fetchRegistry: false

spring:
  zipkin:
    enabled: false
  kafka:
    listener:
      auto-startup: false
