spring:
  datasource:
    # Local development - Reporting user
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:banco_digital_reporting}
    username: report_user
    password: ${REPORTING_DB_PASSWORD:ReportingBD101!}
  cloud:
    vault:
      enabled: false
  jpa:
    show-sql: true

spring.kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
  consumer:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

spring.cloud.stream:
  kafka:
    binder:
      brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

# Secondary datasource for core DB (data migration)
core:
  datasource:
    jdbc-url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/banco_digital_core
    username: core_user
    password: ${CORE_DB_PASSWORD:CoreBanking123!}

logging:
  level:
    com.udea.bancodigital: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
