spring:
  cloud:
    vault:
      enabled: false
    config:
      enabled: false
  jpa:
    show-sql: false

# Disable Eureka for Cloud Run
eureka:
  client:
    enabled: false
    registerWithEureka: false
    fetchRegistry: false

# Disable Kafka consumers for Cloud Run
spring.kafka:
  bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  listener:
    auto-startup: false

spring.cloud.stream:
  kafka:
    binder:
      auto-startup: false

# Disable data migration in cloud
migration:
  enabled: false

logging:
  level:
    root: WARN
    com.udea.bancodigital: INFO

server:
  error:
    include-message: never
    include-stacktrace: never
